---

- name: add password to .pgpass file
  lineinfile:
    dest: "~{{ barman_user }}/.pgpass"
    line: "{{ item.conn_host }}:{{ item.conn_port }}:*:{{ item.conn_user }}:{{ item.conn_password }}"
    owner: "{{ barman_user }}"
    create: yes
    mode: 0600
  with_items: "{{ barman_servers }}"

#TODO: get password from postgresql vars
- name: add password to .pgpass file
  lineinfile:
    dest: "~{{ barman_user }}/.pgpass"
    line: "{{ item.conn_host }}:{{ item.conn_port }}:*:streaming_barman:jaibonnememoire"
    owner: "{{ barman_user }}"
    create: yes
    mode: 0600
  with_items: "{{ barman_servers }}"
  

- name: Create configuration files directory
  file:
    path: "{{ barman_configuration_files_directory }}"
    state: directory

- name: Divert barman main configuration file /etc/barman.conf
  command: dpkg-divert --quiet --local --divert /etc/barman.conf.dpkg-divert --rename /etc/barman.conf
  args:
    creates: "/etc/barman.conf.dpkg-divert"

- name: barman main configuration file /etc/barman.conf
  template:
    src: barman.conf.j2
    dest: /etc/barman.conf
    owner: "{{ barman_user }}"
    mode: 0640

- name: RSYNC | create ssh directory
  file:
    path: ~{{ barman_user }}/.ssh
    owner: "{{ barman_user }}"
    mode: 0755
    state: directory
  when: "{{ barman_use_rsync }}"

- name: RSYNC | private ssh rsa key
  copy:
    dest: ~{{ barman_user }}/.ssh/id_rsa
    owner: "{{ barman_user }}"
    mode: 0600
    content: "{{ barman_ssh_private_key | mandatory }}"
  when: "{{ barman_use_rsync }}"

- name: RSYNC | public ssh rsa key
  copy:
    dest: ~{{ barman_user }}/.ssh/id_rsa.pub
    owner: "{{ barman_user }}"
    mode: 0600
    content: "{{ barman_ssh_public_key | mandatory }}"
  when: "{{ barman_use_rsync }}"

- name: RSYNC | ssh authorized keys
  lineinfile:
    dest: ~{{ barman_user }}/.ssh/authorized_keys
    create: yes
    owner: "{{ barman_user }}"
    mode: 0600
    line: "{{ barman_ssh_public_key | mandatory }}"
  when: "{{ barman_use_rsync }}"

- name: FIXME -- create incoming directory for wals
  file:
    path: "{{ barman_home }}/{{ item.name }}/incoming"
    state: directory
    owner: "{{ barman_user }}"
    mode: 0700
  with_items: "{{ barman_servers }}"

- name: create cron job for backups
  cron:
    user: "{{ barman_user }}"
    name: "barman backup server {{ item.name }}"
    cron_file: barman_backup
    job: "[ -x /usr/bin/barman ] && /usr/bin/barman -q backup {{ item.name }}"
    state: present
    disabled: "{{ item.disabled | default(false) }}"
    minute: "{{ item.minute | mandatory }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
  with_items: "{{ barman_backups_cron }}"
  
- name : STREAMING | Ensure replication slot is created and accessible
  command: "barman receive-wal --create-slot {{ item.name }}"
  become_user: "{{ barman_user }}"
  when: "{{ item.backup_method  == 'postgres' }}"
  with_items : "{{ barman_servers }}"
  ignore_errors: yes
